### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by joshuamorton** [classrank/Grouch#13]
MIT probably

**Comment by mmanguno** [comment]
But GPL though.

**Comment by joshuamorton** [comment]
Meh, MIT is more permissive. I'm not too strong either way.

**Comment by mmanguno** [comment]
This seems like a significant-enough piece of software that GPL'ing it could persuade some other projects to GPL as well to get access to it.

Also, instead of MIT, why not do Apache? All the benefits of MIT permissiveness with some additional protections: 

> This [MIT license] is a fine license for a small program. A larger program usually ought to be copyleft; but if you are set on a lax permissive license for one, we recommend the Apache 2.0 license since it protects users from patent treachery. &mdash; <cite>[FSF](https://www.gnu.org/licenses/license-list.en.html#X11License)</cite>

**Comment by joshuamorton** [comment]
I don't think we care too much about patents, but I'm less opposed to
apache than MIT. Really, I favor MIT because its simple and
straightforward, and there's very little legalspeak and no restriction, so
one doesn't need to worry about copyleft or really anything, they can just
use the software.

As an aside, with other maintainer approval, I'm interested in moving
Grouch to another organization, perhaps "GT-muppets" or somesuch and
developing some additional tools in the same vein as Grouch and
coursesat.tech.

**Comment by mmanguno** [comment]
That's fair, since we're not really dealing with patenting, nor are we interested in copylefting. MIT's fine then.

I'd be fine with moving it to another organization. Makes more sense for it to be in a general GT-tool organization rather than ClassRank.

**Comment by joshuamorton** [comment]
Aight, and yeah I'll get to that second part closer to school, but I'm
probably going to implement a couple of tools and organize them into a
single org:
- Grouch
- coursesat.tech (catalog)
- a course critique?
- a nice alternative to degreeworks
- a csp schedule creator

Not sure if there are any others that should be added to that list, but
that seems like a good start, and each would need to be its own project,
but could be hosted under one roof.

**Comment by mmanguno** [comment]
Alright. I'll make a new issue for moving this out of the Classrank organization. We can close this one when the MIT license is updated.

**Comment by casey2161** [comment]
but why

**Comment by casey2161** [comment]
I recommend against GPL as it's too restricting.

**Comment by mmanguno** [comment]
It's already been decided to use the MIT license.

**Comment by joshuamorton** [comment]
wait we had one the whole time.
