### ISSUE TITLE
Prerequisite parsing does not work for "tagged" courses

### ISSUE THREAD

**Issue by raghavkaul** [classrank/Grouch#5]
At the endpoint for "CHEM1212", the "CHEM1211K" || "CHEM1310" prerequisite shows up as a prerequisite for "CHEM1211" || "K" || "CHEM1310".

[Link](http://ec2-54-201-95-91.us-west-2.compute.amazonaws.com/spring2016/CHEM/1212)

**Comment by joshuamorton** [comment]
Thanks, yeah there are a few regex errors. The relevant regex is here https://github.com/classrank/Grouch/blob/master/grouch/parsers/prerequisite_parser.py#L12

Feel free to submit a pull request, or I'll get to it at some point.

Thanks!
